# Generated by Django 3.2 on 2021-05-05 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
        ('posts', '0002_rename_date_published_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccounts.profile'),
            preserve_default=False,
        ),
    ]
